config/routes.rb
Ping::Application.routes.draw do
  root 'pingas#index'
  resources :pingas
  resources :users
  resources :user_pingas, only:[:update]
  resources :user_categories, only:[:update]

  match 'sessions/new', to: 'sessions#new', via: [:get]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete]


  #connect to iphone
  match 'phone/get_events', to: 'phones#recieve_request_get_events', via: [:get]
  match 'phone/create_event', to: 'phones#recieve_request_create_event', via: [:get] 
  match 'phone/register_rsvp_info', to: 'phones#recieve_request_register_rsvp_info', via: [:get]
  match 'phone/checkforuser', to: 'phones#check_for_user', via: [:get]
  match 'phone/set_radius', to: 'phones#set_radius', via: [:get]
end

app/models/pinga.rb
class Pinga < ActiveRecord::Base
	belongs_to :creator, class_name: "User"
  belongs_to :category
	has_many :user_pingas
	has_many :users, through: :user_pingas

  # validates :status, inclusion: { in: ["pending", "active", "inactive"] }
  validates :title, :description, :address, :category_id, :start_time, :duration, presence: true


  geocoded_by :address
  before_validation :calculate_end_time
  before_save :geocode, :check_status

  def perform
    if Time.now < self.end_time 
      self.status == "active"
    else
      self.status == "expired"
    end
    self.save
    WebsocketRails[:pingas].trigger('update', {id: self.id, status: self.status, category: self.category.title}.to_json)
  end

  def put_in_queue
    Delayed::Job.enqueue(self, 0, self.start_time)
    Delayed::Job.enqueue(self, 0, self.end_time)
  end# Etc/UTC

  private

  def calculate_end_time
    self.end_time = self.start_time + self.duration.hours
  end

  def check_status
    if self.status == "cancelled"
      # do nothing
    elsif self.end_time <= Time.now
      self.status = "expired"
    elsif self.start_time <= Time.now
      self.status = "active"
    elsif self.start_time  >= Time.now
      self.status = "pending"
    else
      self.status = "error unknown check times"
    end
  end


end

app/controllers/pingas_controller.rb
class PingasController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    if request.remote_ip == '127.0.0.1'
      @user.ip_address = '74.122.9.196'
    else
      @user.ip_address = request.remote_ip
    end
    @user.geocode
    @user.update_user_pingas
    @user_marker = @user.marker
    @pinga_markers = pinga_markers
    @pingas_by_received_time = @user.pingas_ordered_by_received_in_listening_radius
    @pingas_by_distance = @user.pingas_ordered_by_distance_in_listening_radius
    @pingas_by_start_time = @user.pingas_ordered_by_start_time_in_listening_radius
    @categories = Category.all
    @pinga = Pinga.new
  end

  def show
    render :json => { show: render_to_string(partial: "pingas/show", locals: { pinga: Pinga.find(params[:id].to_i) }) }
  end

  def destroy
    @pinga = Pinga.find(params[:id])
    @pinga.status = "cancelled"
    if @pinga.save
      render :json => params[:id]
    else
      render :json => false
    end
  end

  private
  
  def pinga_params
    params.require(:pinga).permit(:title, :description, :start_time, :duration, :address, :category_id)
  end
end


def pinga_markers
  pingas = []
  @user.pingas_in_listening_radius.each do |pinga|
    if pinga.status != "expired" && pinga.status != "cancelled"
      marker = { :id         => pinga.id,
                 :latitude   => pinga.latitude,
                 :longitude  => pinga.longitude,
                 :category   => pinga.category.title,
                 :status     => pinga.status,
                 :infowindow => render_to_string(:partial => "/shared/infowindow", :locals => { pinga: pinga })
                 # :picture => {  "url" => "assets/#{pinga.category.title}_#{pinga.status}.png",
                 #                "width" => 20,
                 #                "height" => 34}
      }
      pingas.push(marker)
    end

  end
  @user.pingas_outside_listening_radius.each do |pinga|
    if pinga.status != "expired" && pinga.status != "cancelled"
      marker = { :id         => pinga.id,
                 :latitude   => pinga.latitude,
                 :longitude  => pinga.longitude,
                 :category   => pinga.category.title,
                 :status     => "outside",
                 :infowindow => render_to_string(:partial => "/shared/infowindow", :locals => { pinga: pinga })
      #            :picture => {  "url" => "assets/#{pinga.category.title}_outside.png",
      #                           "width" => 20,
      #                           "height" => 34}
      }
      pingas.push(marker)
    end
  end
  pingas
end

app/views/pingas/_form.html.erb
    <% options = [["1 hour", 1]] %>
    <% (2..12).each do |num| %>
        <% options << ["#{num} hours", num] %>
    <% end %>

  <%= form_for @pinga do |f| %>
    <%= f.text_field :title, placeholder: "Event Title" %><br>
    <%= f.text_area :description, placeholder: "Event Description" %><br>
    <%= f.text_field :address,  id: "autocomplete", placeholder: "Event Address" %><br>
    <%= options_from_collection_for_select(Category.all, :id, :title) %>
    <%= collection_select(:pinga, :category_id, Category.all, :id, :title) %><br>
    <%= f.label :start_time%>
    <span id="now-default-msg">:  defaults to now </span><br>
    <%= link_to("change start time", pinga_path(@pinga), :id =>"change-start") %>
    <%= link_to("make now", pinga_path(@pinga), :id =>"now-start", style:"display:none;") %>
    <%= time_field(:pinga, :start_time, hidden: true) %><p id="today-tomorrow"></p><p id="start-time-validations"></p><br>
    <%= label_tag(:pinga, "Duration")%><br>
    <%= select_tag(:duration, options_for_select(options)) %>
    <%= f.submit "Ping it!", class: "submit" %>
  <% end %>

app/views/pingas/_list.html.erb
<% if list && list.count > 0 %>
    <% list.each do |pinga| %>
        <%= render partial: "pingas/list_item", locals: {pinga: pinga, main_list: main_list} %>
    <% end %>
<% end %>

app/views/pingas/_list_item.html.erb
<li class="ping ping_link <%= "main_list" if main_list %> <%= pinga.category.title %> <%= pinga.status %> <%= pinga.id.to_s %> tab-styles">

  <div class="ping_title" id="<%= pinga.id.to_s %>" >
    <%= image_tag pinga.category.title + "_" + pinga.status + '.png' %>
    <p><%= pinga.title %></p>
    <p><%= @user.distance(pinga) %> mi</p>
    <% if pinga.status == "pending" %>
        <p><%= start_time(pinga) %></p>
    <% end %>
    <p>RSVP Count: <span class="rsvp-count-<%=pinga.id%>"><%= pinga.user_pingas.where(rsvp_status: "attending").count %></span></p>
  </div>
  <% current_user_pinga = @user.user_pingas.find_by_pinga_id(pinga.id)%>
  <% if current_user_pinga %>
    <div class="rsvp-div-pinga-id-<%=pinga.id%>" id="rsvp-id-<%=current_user_pinga.id%>">
      <% if current_user_pinga.rsvp_status == "attending" %>
        <p class="rsvp-conf">You are going!</p>
      <% elsif current_user_pinga.rsvp_status.nil? %>
        <p class="rsvp-conf">You are not going!</p>
      <% elsif current_user_pinga.rsvp_status == "creator" %>
        <p class="rsvp-conf">You are the creator of this event.</p>
      <% else %>
        <p>Error: Check the rsvp_status of userpinga id <%= current_user_pinga.id %></p>
      <% end %>
    </div>
  <% end %>

</li>

app/views/pingas/_new.html.erb
<h2>create a new pingit</h2>
<div id="form">
    <%= render partial: "form" %>
<ul id="errors"></ul>
</div>

app/views/pingas/_show.html.erb
<h2><%= pinga.title%></h2>
<p>Description: <%= pinga.description%></p>
<p>Address: <%= pinga.address%></p>
<p>Category: <%= pinga.category.title if pinga.category %></p>
<% if pinga.start_time %>
  <p>Start Time: <%= pinga.start_time.localtime.strftime("%a, %b %d %Y %l:%M %p") %></p>
<% end %>
<p>Duration: <%= pluralize(pinga.duration, "hour") %></p>
<% if pinga.end_time %>
  <p>End Time: <%= pinga.end_time.localtime.strftime("%a, %b %d %Y %l:%M %p") %></p>
<% end %>
<p>RSVP Count: <%= pinga.user_pingas.where(rsvp_status: "attending").count %></p>
<p>PingIt Creator: <%= pinga.creator.name if pinga.creator %></p>

<% if pinga.creator_id == session[:user_id] %>
    <%= link_to "Delete this PingIt", pinga_path(pinga), id: pinga.id, class: "delete_pinga_button" %>
<% end %>

app/views/pingas/index.html.erb
<div class="index_list" id="index_list">
  <div id="format">
    <% @user.user_categories.each do |uc| %>
        <%= label_tag(uc.category.title, uc.category.title, class:"styled-label") do %>
          <%= check_box_tag(uc.category.title, "1", !(uc.listening_status), {id: uc.category.title}) %>
          <span><%= uc.category.title.downcase %></span>
        <% end %>
    <% end %>
  </div>

  <div id="tabs">
    <ul id="top-tabs">
      <li class="sorter-tabs newest">newest</li><!-- <a href="#tabs-1">newest</a>-->
      <li class="sorter-tabs nearest">nearest</li>
      <li class="sorter-tabs soonest">starting soon</li>
    </ul>
    <div class="scroll" id="tabs-1">
      <ul id="newest" class="ping_list">
          <%= render partial: "list", locals: {list: @pingas_by_received_time, main_list: true } %>
      </ul>
    </div>
    <div class="scroll" id="tabs-2">
      <ul id="nearest" class="ping_list">
          <%= render partial: "list", locals: {list: @pingas_by_distance, main_list: true } %>
      </ul>
    </div>
    <div class="scroll" id="tabs-3">
      <ul id="soonest" class="ping_list">
          <%= render partial: "list", locals: {list: @pingas_by_start_time, main_list: true } %>
      </ul>
    </div>
  </div>
  <!-- this was where the create button originally was-->

</div>
<div class="content" id="show" style="display: none;">
    <%= render partial: "show", locals: {pinga: @pinga} %>
</div>

<div class="content" id="new" style="display: none;">
    <%= render partial: "new", locals: {pinga: @pinga} %>
</div>

<div class="content" id="show_user" style="display: none;">
  <%= render partial: "users/show", locals: {user: @user} %>
</div>