config/routes.rb
Ping::Application.routes.draw do
  root 'pingas#index'
  resources :pingas
  resources :users
  resources :user_pingas, only:[:update]
  resources :user_categories, only:[:update]

  match 'sessions/new', to: 'sessions#new', via: [:get]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete]


  #connect to iphone
  match 'phone/get_events', to: 'phones#recieve_request_get_events', via: [:get]
  match 'phone/create_event', to: 'phones#recieve_request_create_event', via: [:get] 
  match 'phone/register_rsvp_info', to: 'phones#recieve_request_register_rsvp_info', via: [:get]
  match 'phone/checkforuser', to: 'phones#check_for_user', via: [:get]
  match 'phone/set_radius', to: 'phones#set_radius', via: [:get]
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="column-left">
    <br>
    <h1>Ping</h1>
    <p>Create an event that you want to share with others.  Anyone who is listening for your event nearby will be informed of the event with a Ping!</p>
  </div>

  <div class="column-center">
    <br>
    <h1>Gather</h1>
    <p>Spontaneous events happen all over the city every day.  With Ping-It, you can be made aware of these events and stay involved in your community!</p>
  </div>

  <div class="column-right">
    <br>
    <h1>Explore</h1>
    <p>Listen for Pings according to your personal interests and preferred listening distance.  When a new event is created you will be informed right away!</p>
  </div>
</div>

app/views/layouts/_topnav.html.erb
<div id="topnav">
  <div id="inner_top_nav">
    <img id="pinga-logo-sm" src="/assets/logo.png">
    <%= link_to "PingIt", root_path, 'data-no-turbolink' => true, id:"home" %>
    <%= link_to "account", '/', id: "settings" %>
    <%= link_to "create a ping", new_pinga_path, 'class' => 'button', 'id' => 'new_pinga_button' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	   <title>Ping</title>
	   <%= stylesheet_link_tag "application"%>
	   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&libraries=places,geometry"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
        <link href='http://fonts.googleapis.com/css?family=Neuton:200,300,400,700,800' rel='stylesheet' type='text/css'>
      <script type="text/javascri PT" src="/assets/maps.google.infobox.js"></script>
      <%= javascript_include_tag "application"%>
    	  <%= csrf_meta_tags %>
	</head>
	<body>
    <div class="container" style='width: 1100px; height: 520px;'>
        <%= render "layouts/topnav" %>
        <div class="map">
        <%= render partial: "shared/map" %>
        </div>
        <div class="content">
            <%= yield %>
        </div>
    </div>
    <script>google.maps.event.addDomListener(window, 'load', initialize);</script>
	</body>
</html>